"""
REVENUE & COST
Revenue streams, fixed costs, variable costs, and margins

This self-contained study script teaches core business economics and financial
modeling concepts from beginner to advanced level using executable Python examples.

Topics covered:
1. Revenue and revenue streams
2. Fixed costs
3. Variable costs
4. Total costs
5. Contribution margin
6. Gross margin
7. Operating margin
8. Net margin
9. Break-even analysis
10. Unit economics
11. Multiple products and revenue streams
12. Weighted average margins
13. Pricing decisions
14. Discounts and their effect on margins
15. Cost-volume-profit analysis
16. Operating leverage
17. Scenario analysis
18. Sensitivity analysis
19. Capacity constraints
20. Common mistakes and edge cases
21. Financial validation and testing
22. Practical business simulations

All monetary values in this script are illustrative.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
import math


# =============================================================================
# SECTION 1: FUNDAMENTAL TERMINOLOGY
# =============================================================================

"""
Revenue:
    Money earned from selling goods or services.

Revenue Stream:
    A distinct source through which a business earns revenue.

Examples:
    - Product sales
    - Subscription fees
    - Advertising
    - Consulting
    - Licensing
    - Transaction commissions

Fixed Cost:
    A cost that generally does not change with short-term production or sales
    volume within a relevant operating range.

Examples:
    - Office rent
    - Salaried administration
    - Insurance
    - Software subscriptions
    - Depreciation

Variable Cost:
    A cost that changes with production or sales volume.

Examples:
    - Raw materials
    - Product packaging
    - Sales commissions
    - Payment processing fees
    - Shipping per order

Total Cost:
    Fixed Costs + Variable Costs

Margin:
    A measure of how much money remains after certain costs are deducted.

Contribution Margin:
    Revenue - Variable Costs

Gross Margin:
    Revenue - Cost of Goods Sold

Operating Margin:
    Operating Profit / Revenue

Net Margin:
    Net Profit / Revenue
"""


# =============================================================================
# SECTION 2: BASIC REVENUE CALCULATIONS
# =============================================================================

def calculate_revenue(price_per_unit: float, units_sold: int) -> float:
    """
    Calculate revenue from a single product.

    Formula:
        Revenue = Price per Unit × Units Sold

    Raises:
        ValueError if price or units are negative.
    """
    if price_per_unit < 0:
        raise ValueError("Price per unit cannot be negative.")

    if units_sold < 0:
        raise ValueError("Units sold cannot be negative.")

    return price_per_unit * units_sold


# Example: Selling 100 products at 500 currency units each.
product_price = 500.0
units_sold = 100

basic_revenue = calculate_revenue(product_price, units_sold)

print("=" * 80)
print("SECTION 2: BASIC REVENUE")
print(f"Price per unit: {product_price:,.2f}")
print(f"Units sold: {units_sold}")
print(f"Revenue: {basic_revenue:,.2f}")


# =============================================================================
# SECTION 3: REVENUE STREAMS
# =============================================================================

@dataclass
class RevenueStream:
    """
    Represents an independent source of business revenue.

    Examples:
        - Product Sales
        - Monthly Subscription
        - Consulting Services
        - Advertising
    """

    name: str
    unit_price: float
    units_sold: int

    def __post_init__(self) -> None:
        if self.unit_price < 0:
            raise ValueError("Unit price cannot be negative.")

        if self.units_sold < 0:
            raise ValueError("Units sold cannot be negative.")

    @property
    def revenue(self) -> float:
        """Revenue generated by this stream."""
        return self.unit_price * self.units_sold


revenue_streams = [
    RevenueStream("Product Sales", 500.0, 1000),
    RevenueStream("Subscriptions", 300.0, 500),
    RevenueStream("Consulting", 10_000.0, 20),
]

total_revenue = sum(stream.revenue for stream in revenue_streams)

print("\n" + "=" * 80)
print("SECTION 3: MULTIPLE REVENUE STREAMS")

for stream in revenue_streams:
    print(
        f"{stream.name:<20} "
        f"Price: {stream.unit_price:>10,.2f} | "
        f"Units: {stream.units_sold:>6} | "
        f"Revenue: {stream.revenue:>12,.2f}"
    )

print(f"\nTotal Revenue: {total_revenue:,.2f}")


# =============================================================================
# SECTION 4: FIXED COSTS
# =============================================================================

@dataclass
class FixedCost:
    """
    Represents a cost that generally remains constant over a relevant volume range.

    Important:
        Fixed does not mean permanent.

        Rent can increase after lease renewal.
        Salaries can increase after hiring additional employees.

        Fixed cost means that, within the analyzed period and operating range,
        the cost does not directly change with every additional unit sold.
    """

    name: str
    amount: float

    def __post_init__(self) -> None:
        if self.amount < 0:
            raise ValueError("Fixed cost cannot be negative.")


fixed_costs = [
    FixedCost("Office Rent", 50_000.0),
    FixedCost("Salaries", 200_000.0),
    FixedCost("Software", 20_000.0),
    FixedCost("Insurance", 10_000.0),
]

total_fixed_cost = sum(cost.amount for cost in fixed_costs)

print("\n" + "=" * 80)
print("SECTION 4: FIXED COSTS")

for cost in fixed_costs:
    print(f"{cost.name:<20} {cost.amount:>12,.2f}")

print(f"\nTotal Fixed Cost: {total_fixed_cost:,.2f}")


# =============================================================================
# SECTION 5: VARIABLE COSTS
# =============================================================================

@dataclass
class VariableCost:
    """
    Represents a cost incurred per unit or transaction.

    Examples:
        Manufacturing:
            Raw material per unit

        E-commerce:
            Packaging and payment processing per order

        Consulting:
            Contractor payment per project
    """

    name: str
    cost_per_unit: float

    def __post_init__(self) -> None:
        if self.cost_per_unit < 0:
            raise ValueError("Variable cost per unit cannot be negative.")

    def total_cost(self, units: int) -> float:
        """Calculate total variable cost."""
        if units < 0:
            raise ValueError("Units cannot be negative.")

        return self.cost_per_unit * units


variable_costs = [
    VariableCost("Raw Materials", 150.0),
    VariableCost("Packaging", 20.0),
    VariableCost("Payment Processing", 10.0),
]

units_produced = 1000

total_variable_cost = sum(
    cost.total_cost(units_produced)
    for cost in variable_costs
)

variable_cost_per_unit = sum(
    cost.cost_per_unit
    for cost in variable_costs
)

print("\n" + "=" * 80)
print("SECTION 5: VARIABLE COSTS")

for cost in variable_costs:
    print(
        f"{cost.name:<25} "
        f"Per Unit: {cost.cost_per_unit:>10,.2f} | "
        f"Total: {cost.total_cost(units_produced):>12,.2f}"
    )

print(f"\nVariable Cost Per Unit: {variable_cost_per_unit:,.2f}")
print(f"Total Variable Cost: {total_variable_cost:,.2f}")


# =============================================================================
# SECTION 6: TOTAL COST
# =============================================================================

def calculate_total_cost(
    fixed_cost: float,
    variable_cost_per_unit: float,
    units: int,
) -> float:
    """
    Calculate total cost.

    Formula:
        Total Cost = Fixed Cost + Total Variable Cost

        Total Variable Cost = Variable Cost per Unit × Units
    """
    if fixed_cost < 0:
        raise ValueError("Fixed cost cannot be negative.")

    if variable_cost_per_unit < 0:
        raise ValueError("Variable cost per unit cannot be negative.")

    if units < 0:
        raise ValueError("Units cannot be negative.")

    return fixed_cost + variable_cost_per_unit * units


calculated_total_cost = calculate_total_cost(
    fixed_cost=total_fixed_cost,
    variable_cost_per_unit=variable_cost_per_unit,
    units=units_produced,
)

print("\n" + "=" * 80)
print("SECTION 6: TOTAL COST")
print(f"Fixed Cost: {total_fixed_cost:,.2f}")
print(f"Variable Cost: {total_variable_cost:,.2f}")
print(f"Total Cost: {calculated_total_cost:,.2f}")


# =============================================================================
# SECTION 7: PROFIT
# =============================================================================

def calculate_profit(revenue: float, total_cost: float) -> float:
    """
    Calculate accounting profit.

    Formula:
        Profit = Revenue - Total Cost

    A negative result represents a loss.
    """
    return revenue - total_cost


example_revenue = 500.0 * 1000
example_profit = calculate_profit(
    example_revenue,
    calculated_total_cost,
)

print("\n" + "=" * 80)
print("SECTION 7: PROFIT")
print(f"Revenue: {example_revenue:,.2f}")
print(f"Total Cost: {calculated_total_cost:,.2f}")
print(f"Profit: {example_profit:,.2f}")


# =============================================================================
# SECTION 8: CONTRIBUTION MARGIN
# =============================================================================

def contribution_margin_per_unit(
    selling_price: float,
    variable_cost_per_unit: float,
) -> float:
    """
    Calculate contribution margin per unit.

    Formula:
        Contribution Margin per Unit
        = Selling Price per Unit - Variable Cost per Unit

    Contribution margin contributes toward:
        1. Covering fixed costs
        2. Generating profit after fixed costs are covered
    """
    return selling_price - variable_cost_per_unit


def contribution_margin_ratio(
    selling_price: float,
    variable_cost_per_unit: float,
) -> float:
    """
    Calculate contribution margin ratio.

    Formula:
        Contribution Margin Ratio
        = Contribution Margin / Revenue

    For a single unit:
        (Price - Variable Cost) / Price
    """
    if selling_price == 0:
        return 0.0

    return (
        selling_price - variable_cost_per_unit
    ) / selling_price


selling_price = 500.0
variable_cost = 180.0

cm_per_unit = contribution_margin_per_unit(
    selling_price,
    variable_cost,
)

cm_ratio = contribution_margin_ratio(
    selling_price,
    variable_cost,
)

print("\n" + "=" * 80)
print("SECTION 8: CONTRIBUTION MARGIN")
print(f"Selling Price per Unit: {selling_price:,.2f}")
print(f"Variable Cost per Unit: {variable_cost:,.2f}")
print(f"Contribution Margin per Unit: {cm_per_unit:,.2f}")
print(f"Contribution Margin Ratio: {cm_ratio:.2%}")


# =============================================================================
# SECTION 9: BREAK-EVEN ANALYSIS
# =============================================================================

def break_even_units(
    fixed_cost: float,
    selling_price: float,
    variable_cost_per_unit: float,
) -> Optional[float]:
    """
    Calculate break-even sales volume.

    Formula:
        Break-even Units
        = Fixed Cost / Contribution Margin per Unit

    If contribution margin is zero or negative, the business cannot cover
    fixed costs through increased sales under the current economics.
    """
    contribution = selling_price - variable_cost_per_unit

    if contribution <= 0:
        return None

    return fixed_cost / contribution


def break_even_revenue(
    fixed_cost: float,
    contribution_margin_ratio_value: float,
) -> Optional[float]:
    """
    Calculate break-even revenue.

    Formula:
        Break-even Revenue
        = Fixed Cost / Contribution Margin Ratio
    """
    if contribution_margin_ratio_value <= 0:
        return None

    return fixed_cost / contribution_margin_ratio_value


fixed_cost_example = 100_000.0
price_example = 500.0
variable_cost_example = 300.0

break_even_volume = break_even_units(
    fixed_cost_example,
    price_example,
    variable_cost_example,
)

cm_ratio_example = contribution_margin_ratio(
    price_example,
    variable_cost_example,
)

break_even_sales = break_even_revenue(
    fixed_cost_example,
    cm_ratio_example,
)

print("\n" + "=" * 80)
print("SECTION 9: BREAK-EVEN ANALYSIS")
print(f"Fixed Cost: {fixed_cost_example:,.2f}")
print(f"Selling Price: {price_example:,.2f}")
print(f"Variable Cost per Unit: {variable_cost_example:,.2f}")

if break_even_volume is None:
    print("Break-even is impossible with non-positive contribution margin.")
else:
    print(f"Break-even Units: {break_even_volume:,.2f}")
    print(f"Practical Units Required: {math.ceil(break_even_volume)}")

if break_even_sales is None:
    print("Break-even revenue cannot be calculated.")
else:
    print(f"Break-even Revenue: {break_even_sales:,.2f}")


# =============================================================================
# SECTION 10: GROSS MARGIN
# =============================================================================

def gross_profit(revenue: float, cost_of_goods_sold: float) -> float:
    """
    Gross Profit = Revenue - Cost of Goods Sold.

    Cost of Goods Sold, commonly abbreviated as COGS, generally includes
    direct costs associated with producing or acquiring goods sold.
    """
    return revenue - cost_of_goods_sold


def gross_margin(revenue: float, cost_of_goods_sold: float) -> float:
    """
    Gross Margin = Gross Profit / Revenue.

    The result is expressed as a decimal.
    """
    if revenue == 0:
        return 0.0

    return gross_profit(revenue, cost_of_goods_sold) / revenue


revenue_example = 1_000_000.0
cogs_example = 600_000.0

gross_profit_example = gross_profit(
    revenue_example,
    cogs_example,
)

gross_margin_example = gross_margin(
    revenue_example,
    cogs_example,
)

print("\n" + "=" * 80)
print("SECTION 10: GROSS MARGIN")
print(f"Revenue: {revenue_example:,.2f}")
print(f"COGS: {cogs_example:,.2f}")
print(f"Gross Profit: {gross_profit_example:,.2f}")
print(f"Gross Margin: {gross_margin_example:.2%}")


# =============================================================================
# SECTION 11: OPERATING AND NET MARGINS
# =============================================================================

def margin(profit_measure: float, revenue: float) -> float:
    """
    Generic margin calculation.

    Margin = Profit Measure / Revenue
    """
    if revenue == 0:
        return 0.0

    return profit_measure / revenue


financial_example = {
    "revenue": 1_000_000.0,
    "cogs": 550_000.0,
    "operating_expenses": 250_000.0,
    "interest_and_tax": 80_000.0,
}

gross_profit_value = (
    financial_example["revenue"]
    - financial_example["cogs"]
)

operating_profit_value = (
    gross_profit_value
    - financial_example["operating_expenses"]
)

net_profit_value = (
    operating_profit_value
    - financial_example["interest_and_tax"]
)

print("\n" + "=" * 80)
print("SECTION 11: DIFFERENT TYPES OF MARGINS")
print(f"Revenue: {financial_example['revenue']:,.2f}")
print(f"Gross Profit: {gross_profit_value:,.2f}")
print(f"Operating Profit: {operating_profit_value:,.2f}")
print(f"Net Profit: {net_profit_value:,.2f}")
print(f"Gross Margin: {margin(gross_profit_value, financial_example['revenue']):.2%}")
print(f"Operating Margin: {margin(operating_profit_value, financial_example['revenue']):.2%}")
print(f"Net Margin: {margin(net_profit_value, financial_example['revenue']):.2%}")


# =============================================================================
# SECTION 12: UNIT ECONOMICS
# =============================================================================

@dataclass
class UnitEconomics:
    """
    Represents the economics of one unit, customer, order, or transaction.

    Unit economics is useful for answering questions such as:

    - Does each sale create value?
    - Does each customer contribute toward fixed costs?
    - Is growth profitable at the unit level?
    """

    selling_price: float
    variable_cost_per_unit: float

    def __post_init__(self) -> None:
        if self.selling_price < 0:
            raise ValueError("Selling price cannot be negative.")

        if self.variable_cost_per_unit < 0:
            raise ValueError("Variable cost cannot be negative.")

    @property
    def contribution_margin(self) -> float:
        return self.selling_price - self.variable_cost_per_unit

    @property
    def contribution_margin_ratio(self) -> float:
        if self.selling_price == 0:
            return 0.0

        return self.contribution_margin / self.selling_price

    @property
    def is_positive(self) -> bool:
        return self.contribution_margin > 0


unit_economics = UnitEconomics(
    selling_price=1_000.0,
    variable_cost_per_unit=650.0,
)

print("\n" + "=" * 80)
print("SECTION 12: UNIT ECONOMICS")
print(f"Selling Price: {unit_economics.selling_price:,.2f}")
print(f"Variable Cost: {unit_economics.variable_cost_per_unit:,.2f}")
print(f"Contribution Margin: {unit_economics.contribution_margin:,.2f}")
print(
    "Contribution Margin Ratio: "
    f"{unit_economics.contribution_margin_ratio:.2%}"
)
print(f"Positive Unit Economics: {unit_economics.is_positive}")


# =============================================================================
# SECTION 13: A COMPLETE PRODUCT FINANCIAL MODEL
# =============================================================================

@dataclass
class Product:
    """
    Represents a product or service with pricing and cost characteristics.
    """

    name: str
    price: float
    variable_cost_per_unit: float
    units_sold: int

    def __post_init__(self) -> None:
        if self.price < 0:
            raise ValueError("Price cannot be negative.")

        if self.variable_cost_per_unit < 0:
            raise ValueError("Variable cost cannot be negative.")

        if self.units_sold < 0:
            raise ValueError("Units sold cannot be negative.")

    @property
    def revenue(self) -> float:
        return self.price * self.units_sold

    @property
    def total_variable_cost(self) -> float:
        return self.variable_cost_per_unit * self.units_sold

    @property
    def contribution_margin(self) -> float:
        return self.revenue - self.total_variable_cost

    @property
    def contribution_margin_ratio(self) -> float:
        if self.revenue == 0:
            return 0.0

        return self.contribution_margin / self.revenue


@dataclass
class Business:
    """
    Represents a simplified multi-product business.

    The model separates:
        - Product-level variable economics
        - Business-level fixed costs

    This separation is important because fixed costs must eventually be covered
    by the combined contribution margins of products.
    """

    name: str
    products: List[Product] = field(default_factory=list)
    fixed_costs: List[FixedCost] = field(default_factory=list)

    @property
    def total_revenue(self) -> float:
        return sum(product.revenue for product in self.products)

    @property
    def total_variable_cost(self) -> float:
        return sum(
            product.total_variable_cost
            for product in self.products
        )

    @property
    def total_contribution_margin(self) -> float:
        return (
            self.total_revenue
            - self.total_variable_cost
        )

    @property
    def total_fixed_cost(self) -> float:
        return sum(cost.amount for cost in self.fixed_costs)

    @property
    def operating_profit(self) -> float:
        return (
            self.total_contribution_margin
            - self.total_fixed_cost
        )

    @property
    def operating_margin(self) -> float:
        if self.total_revenue == 0:
            return 0.0

        return (
            self.operating_profit
            / self.total_revenue
        )


business = Business(
    name="Example Multi-Product Business",
    products=[
        Product(
            name="Basic Plan",
            price=500.0,
            variable_cost_per_unit=150.0,
            units_sold=1000,
        ),
        Product(
            name="Premium Plan",
            price=1500.0,
            variable_cost_per_unit=400.0,
            units_sold=400,
        ),
        Product(
            name="Consulting",
            price=10_000.0,
            variable_cost_per_unit=3_000.0,
            units_sold=50,
        ),
    ],
    fixed_costs=[
        FixedCost("Salaries", 500_000.0),
        FixedCost("Rent", 100_000.0),
        FixedCost("Technology", 75_000.0),
    ],
)

print("\n" + "=" * 80)
print("SECTION 13: MULTI-PRODUCT BUSINESS MODEL")
print(f"Business: {business.name}\n")

for product in business.products:
    print(product.name)
    print(f"  Revenue: {product.revenue:,.2f}")
    print(f"  Variable Cost: {product.total_variable_cost:,.2f}")
    print(f"  Contribution Margin: {product.contribution_margin:,.2f}")
    print(
        "  Contribution Margin Ratio: "
        f"{product.contribution_margin_ratio:.2%}"
    )

print("\nBusiness Totals")
print(f"Total Revenue: {business.total_revenue:,.2f}")
print(f"Total Variable Cost: {business.total_variable_cost:,.2f}")
print(
    "Total Contribution Margin: "
    f"{business.total_contribution_margin:,.2f}"
)
print(f"Total Fixed Cost: {business.total_fixed_cost:,.2f}")
print(f"Operating Profit: {business.operating_profit:,.2f}")
print(f"Operating Margin: {business.operating_margin:.2%}")


# =============================================================================
# SECTION 14: PRODUCT MIX AND WEIGHTED AVERAGE MARGIN
# =============================================================================

def weighted_average_margin(products: List[Product]) -> float:
    """
    Calculate the business-level contribution margin ratio.

    Important:
        Do not calculate an average by simply averaging percentages.

    Incorrect:
        (50% + 10%) / 2 = 30%

    Correct:
        Total Contribution Margin / Total Revenue

    Revenue volume must influence the weighting.
    """
    total_product_revenue = sum(
        product.revenue
        for product in products
    )

    total_product_contribution = sum(
        product.contribution_margin
        for product in products
    )

    if total_product_revenue == 0:
        return 0.0

    return (
        total_product_contribution
        / total_product_revenue
    )


weighted_margin = weighted_average_margin(
    business.products
)

print("\n" + "=" * 80)
print("SECTION 14: PRODUCT MIX")
print(
    "Weighted Contribution Margin Ratio: "
    f"{weighted_margin:.2%}"
)


# =============================================================================
# SECTION 15: PRICING AND MARGIN RELATIONSHIPS
# =============================================================================

def minimum_price_for_target_margin(
    variable_cost: float,
    target_margin_ratio: float,
) -> Optional[float]:
    """
    Calculate minimum price required for a target contribution margin ratio.

    Formula:
        Target Margin = (Price - Variable Cost) / Price

    Rearranging:
        Price = Variable Cost / (1 - Target Margin)

    Example:
        Variable Cost = 600
        Target Margin = 40%

        Price = 600 / (1 - 0.40)
        Price = 1,000
    """
    if variable_cost < 0:
        raise ValueError("Variable cost cannot be negative.")

    if not 0 <= target_margin_ratio < 1:
        return None

    return variable_cost / (
        1 - target_margin_ratio
    )


target_margin_price = minimum_price_for_target_margin(
    variable_cost=600.0,
    target_margin_ratio=0.40,
)

print("\n" + "=" * 80)
print("SECTION 15: PRICING FOR TARGET MARGIN")
print("Variable Cost per Unit: 600.00")
print("Target Contribution Margin: 40.00%")
print(
    "Required Minimum Price: "
    f"{target_margin_price:,.2f}"
)


# =============================================================================
# SECTION 16: DISCOUNTS AND MARGIN COMPRESSION
# =============================================================================

def apply_discount(
    original_price: float,
    discount_percentage: float,
) -> float:
    """
    Apply a percentage discount.

    Example:
        Original Price = 1,000
        Discount = 20%

        Discounted Price = 800
    """
    if original_price < 0:
        raise ValueError("Original price cannot be negative.")

    if not 0 <= discount_percentage <= 1:
        raise ValueError(
            "Discount percentage must be between 0 and 1."
        )

    return original_price * (
        1 - discount_percentage
    )


original_price = 1_000.0
discount_rate = 0.20
constant_variable_cost = 600.0

discounted_price = apply_discount(
    original_price,
    discount_rate,
)

original_margin = contribution_margin_ratio(
    original_price,
    constant_variable_cost,
)

discounted_margin = contribution_margin_ratio(
    discounted_price,
    constant_variable_cost,
)

print("\n" + "=" * 80)
print("SECTION 16: DISCOUNTS AND MARGIN COMPRESSION")
print(f"Original Price: {original_price:,.2f}")
print(f"Discount: {discount_rate:.2%}")
print(f"Discounted Price: {discounted_price:,.2f}")
print(f"Variable Cost: {constant_variable_cost:,.2f}")
print(f"Original Margin: {original_margin:.2%}")
print(f"Discounted Margin: {discounted_margin:.2%}")

"""
Important pricing insight:

A 20% price discount does not necessarily cause a 20% reduction in profit.

When variable costs remain unchanged, contribution margin can decline much more
dramatically than the percentage discount itself.
"""


# =============================================================================
# SECTION 17: BREAK-EVEN AFTER A DISCOUNT
# =============================================================================

def units_required_for_target_profit(
    fixed_cost: float,
    target_profit: float,
    selling_price: float,
    variable_cost_per_unit: float,
) -> Optional[float]:
    """
    Calculate units required to achieve a target profit.

    Formula:
        Required Units
        = (Fixed Costs + Target Profit)
          / Contribution Margin per Unit
    """
    contribution = (
        selling_price
        - variable_cost_per_unit
    )

    if contribution <= 0:
        return None

    return (
        fixed_cost + target_profit
    ) / contribution


fixed_cost_for_pricing = 100_000.0
target_profit = 50_000.0

units_before_discount = units_required_for_target_profit(
    fixed_cost_for_pricing,
    target_profit,
    original_price,
    constant_variable_cost,
)

units_after_discount = units_required_for_target_profit(
    fixed_cost_for_pricing,
    target_profit,
    discounted_price,
    constant_variable_cost,
)

print("\n" + "=" * 80)
print("SECTION 17: SALES VOLUME REQUIRED AFTER DISCOUNT")

print(
    "Units Required Before Discount: "
    f"{units_before_discount:,.2f}"
)

print(
    "Units Required After Discount: "
    f"{units_after_discount:,.2f}"
)

if units_before_discount and units_after_discount:
    increase = (
        units_after_discount
        / units_before_discount
        - 1
    )

    print(
        "Increase in Required Volume: "
        f"{increase:.2%}"
    )


# =============================================================================
# SECTION 18: COST-VOLUME-PROFIT ANALYSIS
# =============================================================================

def cost_volume_profit_table(
    fixed_cost: float,
    selling_price: float,
    variable_cost_per_unit: float,
    unit_levels: List[int],
) -> List[Dict[str, float]]:
    """
    Create a Cost-Volume-Profit table.

    Cost-Volume-Profit analysis studies how changes in:
        - Sales volume
        - Selling price
        - Variable cost
        - Fixed cost

    affect profit.
    """
    results = []

    for units in unit_levels:
        revenue = selling_price * units
        variable_cost = variable_cost_per_unit * units
        total_cost = fixed_cost + variable_cost
        profit = revenue - total_cost

        results.append(
            {
                "units": units,
                "revenue": revenue,
                "variable_cost": variable_cost,
                "fixed_cost": fixed_cost,
                "total_cost": total_cost,
                "profit": profit,
            }
        )

    return results


cvp_results = cost_volume_profit_table(
    fixed_cost=100_000.0,
    selling_price=500.0,
    variable_cost_per_unit=300.0,
    unit_levels=[0, 100, 250, 500, 750, 1000],
)

print("\n" + "=" * 80)
print("SECTION 18: COST-VOLUME-PROFIT ANALYSIS")
print(
    f"{'Units':>8} "
    f"{'Revenue':>15} "
    f"{'Variable Cost':>15} "
    f"{'Total Cost':>15} "
    f"{'Profit':>15}"
)

for row in cvp_results:
    print(
        f"{row['units']:>8,} "
        f"{row['revenue']:>15,.2f} "
        f"{row['variable_cost']:>15,.2f} "
        f"{row['total_cost']:>15,.2f} "
        f"{row['profit']:>15,.2f}"
    )


# =============================================================================
# SECTION 19: OPERATING LEVERAGE
# =============================================================================

def operating_leverage(
    contribution_margin_value: float,
    operating_profit_value: float,
) -> Optional[float]:
    """
    Simplified Degree of Operating Leverage.

    DOL = Contribution Margin / Operating Profit

    A high operating leverage business has relatively high fixed costs.

    Consequences:
        - Revenue growth can increase profits rapidly.
        - Revenue decline can reduce profits rapidly.

    The metric becomes unstable near zero operating profit and is not meaningful
    when operating profit is exactly zero.
    """
    if operating_profit_value == 0:
        return None

    return (
        contribution_margin_value
        / operating_profit_value
    )


operating_leverage_example = operating_leverage(
    contribution_margin_value=500_000.0,
    operating_profit_value=100_000.0,
)

print("\n" + "=" * 80)
print("SECTION 19: OPERATING LEVERAGE")

if operating_leverage_example is None:
    print(
        "Operating leverage is undefined because operating profit is zero."
    )
else:
    print(
        "Degree of Operating Leverage: "
        f"{operating_leverage_example:.2f}"
    )


# =============================================================================
# SECTION 20: SCENARIO ANALYSIS
# =============================================================================

@dataclass
class Scenario:
    """
    Represents a financial scenario.

    Scenario analysis helps evaluate uncertainty by changing assumptions.
    """

    name: str
    price: float
    variable_cost_per_unit: float
    units_sold: int
    fixed_cost: float

    def evaluate(self) -> Dict[str, float]:
        revenue = self.price * self.units_sold

        total_variable_cost = (
            self.variable_cost_per_unit
            * self.units_sold
        )

        contribution_margin_value = (
            revenue
            - total_variable_cost
        )

        profit = (
            contribution_margin_value
            - self.fixed_cost
        )

        profit_margin_value = (
            profit / revenue
            if revenue != 0
            else 0.0
        )

        return {
            "revenue": revenue,
            "variable_cost": total_variable_cost,
            "contribution_margin": contribution_margin_value,
            "fixed_cost": self.fixed_cost,
            "profit": profit,
            "profit_margin": profit_margin_value,
        }


scenarios = [
    Scenario(
        "Conservative",
        price=1000.0,
        variable_cost_per_unit=650.0,
        units_sold=500,
        fixed_cost=200_000.0,
    ),
    Scenario(
        "Expected",
        price=1000.0,
        variable_cost_per_unit=600.0,
        units_sold=800,
        fixed_cost=200_000.0,
    ),
    Scenario(
        "Optimistic",
        price=1100.0,
        variable_cost_per_unit=550.0,
        units_sold=1200,
        fixed_cost=220_000.0,
    ),
]

print("\n" + "=" * 80)
print("SECTION 20: SCENARIO ANALYSIS")

for scenario in scenarios:
    result = scenario.evaluate()

    print(f"\n{scenario.name} Scenario")
    print(f"Revenue: {result['revenue']:,.2f}")
    print(
        "Contribution Margin: "
        f"{result['contribution_margin']:,.2f}"
    )
    print(f"Profit: {result['profit']:,.2f}")
    print(
        "Profit Margin: "
        f"{result['profit_margin']:.2%}"
    )


# =============================================================================
# SECTION 21: SENSITIVITY ANALYSIS
# =============================================================================

def price_sensitivity_analysis(
    base_price: float,
    variable_cost: float,
    units: int,
    fixed_cost: float,
    percentage_changes: List[float],
) -> List[Dict[str, float]]:
    """
    Evaluate how changes in price affect revenue and profit.

    A percentage change of:
        -0.10 means a 10% decrease
         0.10 means a 10% increase
    """
    results = []

    for change in percentage_changes:
        new_price = base_price * (
            1 + change
        )

        revenue = new_price * units

        total_variable_cost = (
            variable_cost * units
        )

        profit = (
            revenue
            - total_variable_cost
            - fixed_cost
        )

        results.append(
            {
                "price_change": change,
                "price": new_price,
                "revenue": revenue,
                "profit": profit,
            }
        )

    return results


sensitivity_results = price_sensitivity_analysis(
    base_price=1000.0,
    variable_cost=600.0,
    units=1000,
    fixed_cost=200_000.0,
    percentage_changes=[
        -0.20,
        -0.10,
        -0.05,
        0.00,
        0.05,
        0.10,
        0.20,
    ],
)

print("\n" + "=" * 80)
print("SECTION 21: PRICE SENSITIVITY ANALYSIS")
print(
    f"{'Price Change':>15} "
    f"{'New Price':>15} "
    f"{'Revenue':>15} "
    f"{'Profit':>15}"
)

for result in sensitivity_results:
    print(
        f"{result['price_change']:>14.2%} "
        f"{result['price']:>15,.2f} "
        f"{result['revenue']:>15,.2f} "
        f"{result['profit']:>15,.2f}"
    )


# =============================================================================
# SECTION 22: CAPACITY CONSTRAINTS
# =============================================================================

def maximum_profit_with_capacity(
    price: float,
    variable_cost_per_unit: float,
    fixed_cost: float,
    market_demand: int,
    production_capacity: int,
) -> Dict[str, float]:
    """
    Analyze profit when production capacity limits sales.

    Actual sales cannot exceed the lower of:
        - Market demand
        - Production capacity
    """
    if market_demand < 0:
        raise ValueError(
            "Market demand cannot be negative."
        )

    if production_capacity < 0:
        raise ValueError(
            "Production capacity cannot be negative."
        )

    units_sold = min(
        market_demand,
        production_capacity,
    )

    revenue = price * units_sold

    variable_cost = (
        variable_cost_per_unit
        * units_sold
    )

    profit = (
        revenue
        - variable_cost
        - fixed_cost
    )

    return {
        "units_sold": units_sold,
        "revenue": revenue,
        "variable_cost": variable_cost,
        "profit": profit,
    }


capacity_result = maximum_profit_with_capacity(
    price=1000.0,
    variable_cost_per_unit=600.0,
    fixed_cost=150_000.0,
    market_demand=1000,
    production_capacity=700,
)

print("\n" + "=" * 80)
print("SECTION 22: CAPACITY CONSTRAINTS")
print(
    "Market Demand: "
    f"{1_000:,}"
)
print(
    "Production Capacity: "
    f"{700:,}"
)
print(
    "Actual Units Sold: "
    f"{int(capacity_result['units_sold']):,}"
)
print(
    "Revenue: "
    f"{capacity_result['revenue']:,.2f}"
)
print(
    "Profit: "
    f"{capacity_result['profit']:,.2f}"
)


# =============================================================================
# SECTION 23: STEP FIXED COSTS
# =============================================================================

def calculate_step_fixed_cost(
    units: int,
    capacity_per_facility: int,
    facility_cost: float,
) -> float:
    """
    Demonstrate step-fixed costs.

    Some costs remain fixed only within a capacity range.

    Example:
        One warehouse handles up to 1,000 units.
        Demand above 1,000 units requires another warehouse.

    This creates a step pattern rather than a perfectly flat fixed cost.
    """
    if units <= 0:
        return 0.0

    facilities_required = math.ceil(
        units / capacity_per_facility
    )

    return (
        facilities_required
        * facility_cost
    )


print("\n" + "=" * 80)
print("SECTION 23: STEP FIXED COSTS")

for units in [500, 1000, 1001, 1500, 2000, 2500]:
    warehouse_cost = calculate_step_fixed_cost(
        units=units,
        capacity_per_facility=1000,
        facility_cost=50_000.0,
    )

    print(
        f"Units: {units:>5,} | "
        f"Step Fixed Cost: {warehouse_cost:>10,.2f}"
    )


# =============================================================================
# SECTION 24: MIXED COSTS
# =============================================================================

def calculate_mixed_cost(
    fixed_component: float,
    variable_component_per_unit: float,
    units: int,
) -> float:
    """
    Mixed costs contain both fixed and variable components.

    Formula:
        Mixed Cost
        = Fixed Component
          + Variable Component × Units

    Example:
        Electricity may include:
            - Fixed connection charge
            - Usage-based consumption charge
    """
    return (
        fixed_component
        + variable_component_per_unit
        * units
    )


mixed_cost_example = calculate_mixed_cost(
    fixed_component=10_000.0,
    variable_component_per_unit=5.0,
    units=5000,
)

print("\n" + "=" * 80)
print("SECTION 24: MIXED COSTS")
print(f"Mixed Cost: {mixed_cost_example:,.2f}")


# =============================================================================
# SECTION 25: MARGIN VS MARKUP
# =============================================================================

def margin_percentage(
    selling_price: float,
    cost: float,
) -> float:
    """
    Margin Percentage:
        (Selling Price - Cost) / Selling Price
    """
    if selling_price == 0:
        return 0.0

    return (
        selling_price - cost
    ) / selling_price


def markup_percentage(
    selling_price: float,
    cost: float,
) -> Optional[float]:
    """
    Markup Percentage:
        (Selling Price - Cost) / Cost

    Cost equal to zero makes markup mathematically undefined.
    """
    if cost == 0:
        return None

    return (
        selling_price - cost
    ) / cost


price_for_comparison = 1000.0
cost_for_comparison = 600.0

margin_value = margin_percentage(
    price_for_comparison,
    cost_for_comparison,
)

markup_value = markup_percentage(
    price_for_comparison,
    cost_for_comparison,
)

print("\n" + "=" * 80)
print("SECTION 25: MARGIN VS MARKUP")
print(f"Selling Price: {price_for_comparison:,.2f}")
print(f"Cost: {cost_for_comparison:,.2f}")
print(f"Margin: {margin_value:.2%}")

if markup_value is not None:
    print(f"Markup: {markup_value:.2%}")

"""
Margin and markup are commonly confused.

For the same transaction:

Cost = 600
Price = 1,000
Profit = 400

Margin = 400 / 1,000 = 40%
Markup = 400 / 600 = 66.67%

They use different denominators.
"""


# =============================================================================
# SECTION 26: ZERO AND NEGATIVE CONTRIBUTION MARGINS
# =============================================================================

edge_case_examples = [
    ("Positive Contribution", 1000.0, 600.0),
    ("Zero Contribution", 1000.0, 1000.0),
    ("Negative Contribution", 1000.0, 1200.0),
]

print("\n" + "=" * 80)
print("SECTION 26: CONTRIBUTION MARGIN EDGE CASES")

for name, price, variable_cost in edge_case_examples:
    contribution = (
        price - variable_cost
    )

    print(
        f"{name:<25} "
        f"Price: {price:>10,.2f} | "
        f"Variable Cost: {variable_cost:>10,.2f} | "
        f"Contribution: {contribution:>10,.2f}"
    )


# =============================================================================
# SECTION 27: REVENUE GROWTH DOES NOT ALWAYS MEAN PROFIT GROWTH
# =============================================================================

def compare_growth_scenarios() -> None:
    """
    Demonstrate why revenue growth alone can be misleading.

    Scenario A:
        Lower revenue but healthy contribution margin.

    Scenario B:
        Higher revenue but weak contribution margin.
    """

    scenario_a = {
        "revenue": 1_000_000.0,
        "variable_cost": 500_000.0,
        "fixed_cost": 300_000.0,
    }

    scenario_b = {
        "revenue": 1_500_000.0,
        "variable_cost": 1_250_000.0,
        "fixed_cost": 300_000.0,
    }

    for name, data in [
        ("Scenario A", scenario_a),
        ("Scenario B", scenario_b),
    ]:
        contribution = (
            data["revenue"]
            - data["variable_cost"]
        )

        profit = (
            contribution
            - data["fixed_cost"]
        )

        print(f"\n{name}")
        print(f"Revenue: {data['revenue']:,.2f}")
        print(f"Contribution Margin: {contribution:,.2f}")
        print(f"Profit: {profit:,.2f}")


print("\n" + "=" * 80)
print("SECTION 27: REVENUE GROWTH VS PROFIT")
compare_growth_scenarios()


# =============================================================================
# SECTION 28: CUSTOMER-LEVEL UNIT ECONOMICS
# =============================================================================

@dataclass
class CustomerEconomics:
    """
    Simplified customer economics model.

    Revenue can be compared against the variable cost of serving the customer.

    For subscription businesses, a customer may generate recurring revenue over
    multiple periods.
    """

    monthly_revenue: float
    monthly_variable_cost: float
    expected_months: int
    acquisition_cost: float

    @property
    def lifetime_revenue(self) -> float:
        return (
            self.monthly_revenue
            * self.expected_months
        )

    @property
    def lifetime_variable_cost(self) -> float:
        return (
            self.monthly_variable_cost
            * self.expected_months
        )

    @property
    def lifetime_contribution_before_acquisition(
        self,
    ) -> float:
        return (
            self.lifetime_revenue
            - self.lifetime_variable_cost
        )

    @property
    def customer_profitability(self) -> float:
        return (
            self.lifetime_contribution_before_acquisition
            - self.acquisition_cost
        )


customer = CustomerEconomics(
    monthly_revenue=1000.0,
    monthly_variable_cost=300.0,
    expected_months=12,
    acquisition_cost=4000.0,
)

print("\n" + "=" * 80)
print("SECTION 28: CUSTOMER-LEVEL ECONOMICS")
print(f"Lifetime Revenue: {customer.lifetime_revenue:,.2f}")
print(
    "Lifetime Variable Cost: "
    f"{customer.lifetime_variable_cost:,.2f}"
)
print(
    "Lifetime Contribution Before Acquisition: "
    f"{customer.lifetime_contribution_before_acquisition:,.2f}"
)
print(
    "Customer Profitability: "
    f"{customer.customer_profitability:,.2f}"
)


# =============================================================================
# SECTION 29: MARGIN OF SAFETY
# =============================================================================

def margin_of_safety(
    actual_units: int,
    break_even_units_value: float,
) -> float:
    """
    Margin of Safety measures how far current sales exceed break-even sales.

    Formula:
        (Actual Sales - Break-even Sales) / Actual Sales
    """
    if actual_units <= 0:
        return 0.0

    return (
        actual_units
        - break_even_units_value
    ) / actual_units


break_even_example = break_even_units(
    fixed_cost=100_000.0,
    selling_price=500.0,
    variable_cost_per_unit=300.0,
)

actual_units_example = 750

safety_margin = margin_of_safety(
    actual_units_example,
    break_even_example
    if break_even_example is not None
    else 0,
)

print("\n" + "=" * 80)
print("SECTION 29: MARGIN OF SAFETY")
print(f"Actual Units Sold: {actual_units_example:,}")
print(
    "Break-even Units: "
    f"{break_even_example:,.2f}"
)
print(
    "Margin of Safety: "
    f"{safety_margin:.2%}"
)


# =============================================================================
# SECTION 30: BUSINESS DASHBOARD
# =============================================================================

def print_business_dashboard(
    business_model: Business,
) -> None:
    """
    Print a compact financial dashboard.
    """
    print("\n" + "=" * 80)
    print("SECTION 30: BUSINESS DASHBOARD")
    print(f"Business: {business_model.name}")
    print("-" * 80)
    print(
        f"Revenue: "
        f"{business_model.total_revenue:,.2f}"
    )
    print(
        f"Variable Costs: "
        f"{business_model.total_variable_cost:,.2f}"
    )
    print(
        f"Contribution Margin: "
        f"{business_model.total_contribution_margin:,.2f}"
    )
    print(
        f"Contribution Margin Ratio: "
        f"{weighted_average_margin(business_model.products):.2%}"
    )
    print(
        f"Fixed Costs: "
        f"{business_model.total_fixed_cost:,.2f}"
    )
    print(
        f"Operating Profit: "
        f"{business_model.operating_profit:,.2f}"
    )
    print(
        f"Operating Margin: "
        f"{business_model.operating_margin:.2%}"
    )

    if business_model.operating_profit > 0:
        status = "Profitable"
    elif business_model.operating_profit < 0:
        status = "Loss-making"
    else:
        status = "Break-even"

    print(f"Financial Status: {status}")


print_business_dashboard(business)


# =============================================================================
# SECTION 31: VALIDATION AND COMMON FINANCIAL MODELING ERRORS
# =============================================================================

def validate_business_inputs(
    price: float,
    variable_cost: float,
    fixed_cost: float,
    units: int,
) -> List[str]:
    """
    Validate basic business assumptions.

    Returns a list of warnings instead of raising exceptions so that the caller
    can inspect multiple potential issues simultaneously.
    """
    warnings = []

    if price < 0:
        warnings.append(
            "Selling price is negative."
        )

    if variable_cost < 0:
        warnings.append(
            "Variable cost is negative."
        )

    if fixed_cost < 0:
        warnings.append(
            "Fixed cost is negative."
        )

    if units < 0:
        warnings.append(
            "Sales volume is negative."
        )

    if price > 0 and variable_cost > price:
        warnings.append(
            "Variable cost exceeds selling price, creating negative "
            "contribution margin."
        )

    if units == 0 and fixed_cost > 0:
        warnings.append(
            "No sales volume exists while fixed costs remain."
        )

    return warnings


validation_examples = [
    (1000.0, 600.0, 100_000.0, 1000),
    (1000.0, 1200.0, 100_000.0, 1000),
    (0.0, 0.0, 100_000.0, 0),
]

print("\n" + "=" * 80)
print("SECTION 31: INPUT VALIDATION")

for example in validation_examples:
    warnings = validate_business_inputs(
        price=example[0],
        variable_cost=example[1],
        fixed_cost=example[2],
        units=example[3],
    )

    print(f"\nInputs: {example}")

    if warnings:
        for warning in warnings:
            print(f"WARNING: {warning}")
    else:
        print("No validation warnings.")


# =============================================================================
# SECTION 32: SIMPLE TESTS
# =============================================================================

def run_tests() -> None:
    """
    Execute basic assertions.

    Assertions help detect incorrect formulas during development.
    """

    assert calculate_revenue(
        100.0,
        10,
    ) == 1000.0

    assert contribution_margin_per_unit(
        1000.0,
        600.0,
    ) == 400.0

    assert contribution_margin_ratio(
        1000.0,
        600.0,
    ) == 0.4

    assert gross_profit(
        1000.0,
        600.0,
    ) == 400.0

    assert gross_margin(
        1000.0,
        600.0,
    ) == 0.4

    assert break_even_units(
        100_000.0,
        500.0,
        300.0,
    ) == 500.0

    assert break_even_units(
        100_000.0,
        500.0,
        500.0,
    ) is None

    assert break_even_units(
        100_000.0,
        500.0,
        600.0,
    ) is None

    assert minimum_price_for_target_margin(
        600.0,
        0.40,
    ) == 1000.0

    assert apply_discount(
        1000.0,
        0.20,
    ) == 800.0

    assert margin(
        200.0,
        1000.0,
    ) == 0.2

    print("\n" + "=" * 80)
    print("SECTION 32: TESTING")
    print("All tests passed successfully.")


run_tests()


# =============================================================================
# SECTION 33: IMPORTANT PRACTICAL PRINCIPLES
# =============================================================================

print("\n" + "=" * 80)
print("SECTION 33: PRACTICAL PRINCIPLES")

principles = [
    (
        "Revenue is not profit. "
        "A business can increase revenue while losing money."
    ),
    (
        "Contribution margin determines whether additional sales help cover "
        "fixed costs under the current cost structure."
    ),
    (
        "Fixed costs are fixed only within a relevant operating range and time "
        "period."
    ),
    (
        "Average percentages should generally be weighted by the underlying "
        "economic volume, such as revenue."
    ),
    (
        "Discounting can significantly reduce profit because many variable "
        "costs do not decrease when selling prices fall."
    ),
    (
        "High fixed costs create operating leverage, increasing both upside "
        "and downside sensitivity to changes in revenue."
    ),
    (
        "Positive unit economics does not guarantee total profitability if "
        "fixed costs exceed total contribution margin."
    ),
    (
        "A business should distinguish margin from markup because they use "
        "different denominators."
    ),
    (
        "Capacity constraints can prevent a business from converting market "
        "demand into actual revenue."
    ),
    (
        "Financial models should validate assumptions, handle zero revenue, "
        "and avoid division-by-zero errors."
    ),
]

for number, principle in enumerate(
    principles,
    start=1,
):
    print(f"{number}. {principle}")


# =============================================================================
# SECTION 34: FINAL INTEGRATED SIMULATION
# =============================================================================

def integrated_business_simulation() -> None:
    """
    Integrate revenue streams, variable costs, fixed costs, contribution margin,
    operating profit, break-even analysis, and sensitivity concepts.
    """

    print("\n" + "=" * 80)
    print("SECTION 34: INTEGRATED BUSINESS SIMULATION")

    simulation_business = Business(
        name="Integrated Example Company",
        products=[
            Product(
                name="Consumer Product",
                price=1200.0,
                variable_cost_per_unit=650.0,
                units_sold=1500,
            ),
            Product(
                name="Business Subscription",
                price=5000.0,
                variable_cost_per_unit=1200.0,
                units_sold=300,
            ),
            Product(
                name="Professional Service",
                price=20_000.0,
                variable_cost_per_unit=8_000.0,
                units_sold=80,
            ),
        ],
        fixed_costs=[
            FixedCost(
                "Management and Administration",
                800_000.0,
            ),
            FixedCost(
                "Technology Infrastructure",
                250_000.0,
            ),
            FixedCost(
                "Facilities",
                150_000.0,
            ),
        ],
    )

    print_business_dashboard(
        simulation_business
    )

    print("\nRevenue Stream Contribution")

    for product in simulation_business.products:
        revenue_share = (
            product.revenue
            / simulation_business.total_revenue
            if simulation_business.total_revenue != 0
            else 0
        )

        print(
            f"{product.name:<25} "
            f"Revenue Share: {revenue_share:.2%} | "
            f"Contribution Margin: "
            f"{product.contribution_margin_ratio:.2%}"
        )

    print("\nInterpretation Logic")

    if simulation_business.operating_profit > 0:
        print(
            "The combined contribution margins exceed fixed costs."
        )
    else:
        print(
            "The combined contribution margins do not cover fixed costs."
        )

    print(
        "The financial outcome depends not only on total revenue but also on "
        "product mix, contribution margins, fixed-cost structure, pricing, "
        "volume, and capacity."
    )


integrated_business_simulation()

print("\n" + "=" * 80)
print("END OF REVENUE & COST STUDY SCRIPT")
print("=" * 80)
