-- PostgreSQL 14+.
-- Analytical model for sales performance, customer cohorts, and product hierarchy.
-- CTEs are query-scoped named relations; they do not automatically persist data.

BEGIN;

CREATE SCHEMA IF NOT EXISTS cte_lab;
SET search_path TO cte_lab, public;

CREATE TABLE IF NOT EXISTS customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    region TEXT NOT NULL,
    signup_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL UNIQUE,
    parent_category_id BIGINT REFERENCES categories(category_id)
        ON DELETE RESTRICT,
    CHECK (parent_category_id IS NULL OR parent_category_id <> category_id)
);

CREATE TABLE IF NOT EXISTS products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(category_id),
    unit_cost NUMERIC(12, 2) NOT NULL CHECK (unit_cost >= 0),
    list_price NUMERIC(12, 2) NOT NULL CHECK (list_price >= 0)
);

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(customer_id),
    order_date DATE NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN ('completed', 'cancelled', 'refunded', 'pending')
    )
);

CREATE TABLE IF NOT EXISTS order_items (
    order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    PRIMARY KEY (order_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_orders_status_date
    ON orders(status, order_date);

CREATE INDEX IF NOT EXISTS idx_orders_customer_date
    ON orders(customer_id, order_date);

CREATE INDEX IF NOT EXISTS idx_order_items_product
    ON order_items(product_id);

INSERT INTO customers
    (customer_id, customer_name, region, signup_date)
VALUES
    (1, 'Asha Sharma', 'North', DATE '2025-01-10'),
    (2, 'Rohan Verma', 'South', DATE '2025-02-14'),
    (3, 'Meera Singh', 'North', DATE '2025-03-02'),
    (4, 'Kabir Rao', 'West', DATE '2025-04-20'),
    (5, 'Ira Das', 'South', DATE '2025-05-01')
ON CONFLICT (customer_id) DO NOTHING;

INSERT INTO categories
    (category_id, category_name, parent_category_id)
VALUES
    (1, 'Electronics', NULL),
    (2, 'Computers', 1),
    (3, 'Accessories', 1),
    (4, 'Office Supplies', NULL)
ON CONFLICT (category_id) DO NOTHING;

INSERT INTO products
    (product_id, product_name, category_id, unit_cost, list_price)
VALUES
    (1, 'Laptop', 2, 42000, 60000),
    (2, 'Monitor', 2, 8000, 12000),
    (3, 'Keyboard', 3, 900, 1800),
    (4, 'Notebook', 4, 30, 60)
ON CONFLICT (product_id) DO NOTHING;

INSERT INTO orders
    (order_id, customer_id, order_date, status)
VALUES
    (101, 1, DATE '2025-01-15', 'completed'),
    (102, 1, DATE '2025-02-10', 'completed'),
    (103, 2, DATE '2025-02-18', 'completed'),
    (104, 2, DATE '2025-03-04', 'cancelled'),
    (105, 3, DATE '2025-03-12', 'completed'),
    (106, 3, DATE '2025-04-11', 'completed'),
    (107, 4, DATE '2025-04-25', 'completed'),
    (108, 5, DATE '2025-05-10', 'pending'),
    (109, 1, DATE '2025-05-18', 'refunded'),
    (110, 5, DATE '2025-06-02', 'completed')
ON CONFLICT (order_id) DO NOTHING;

INSERT INTO order_items
    (order_id, product_id, quantity, unit_price)
VALUES
    (101, 1, 1, 60000),
    (101, 3, 2, 1800),
    (102, 2, 1, 12000),
    (103, 3, 3, 1800),
    (104, 1, 1, 60000),
    (105, 1, 1, 58000),
    (105, 4, 10, 60),
    (106, 2, 2, 11500),
    (107, 4, 20, 60),
    (108, 3, 1, 1800),
    (109, 1, 1, 60000),
    (110, 2, 1, 12000)
ON CONFLICT (order_id, product_id) DO NOTHING;

-- Reusable logical stage: recognized order lines exclude cancelled, refunded,
-- and pending orders before any downstream aggregation occurs.
WITH completed_lines AS (
    SELECT
        o.order_id,
        o.customer_id,
        o.order_date,
        oi.product_id,
        oi.quantity,
        oi.unit_price,
        p.unit_cost,
        p.category_id,
        oi.quantity * oi.unit_price AS line_revenue,
        oi.quantity * (oi.unit_price - p.unit_cost) AS line_profit
    FROM orders AS o
    JOIN order_items AS oi USING (order_id)
    JOIN products AS p USING (product_id)
    WHERE o.status = 'completed'
)
SELECT
    c.customer_name,
    COUNT(DISTINCT cl.order_id) AS completed_orders,
    COALESCE(SUM(cl.line_revenue), 0)::NUMERIC(14, 2) AS recognized_revenue,
    COALESCE(SUM(cl.line_profit), 0)::NUMERIC(14, 2) AS gross_profit
FROM customers AS c
LEFT JOIN completed_lines AS cl USING (customer_id)
GROUP BY c.customer_id, c.customer_name
ORDER BY recognized_revenue DESC, c.customer_name;

-- Chained CTEs separate filtering, aggregation, and analytical ranking.
WITH
completed_lines AS (
    SELECT
        oi.product_id,
        oi.quantity,
        oi.unit_price,
        p.unit_cost,
        p.category_id
    FROM orders AS o
    JOIN order_items AS oi USING (order_id)
    JOIN products AS p USING (product_id)
    WHERE o.status = 'completed'
),
category_totals AS (
    SELECT
        c.category_id,
        c.category_name,
        SUM(cl.quantity) AS units_sold,
        SUM(cl.quantity * cl.unit_price) AS revenue,
        SUM(cl.quantity * (cl.unit_price - cl.unit_cost)) AS gross_profit
    FROM completed_lines AS cl
    JOIN categories AS c USING (category_id)
    GROUP BY c.category_id, c.category_name
),
ranked_categories AS (
    SELECT
        *,
        DENSE_RANK() OVER (ORDER BY gross_profit DESC) AS profit_rank,
        SUM(gross_profit) OVER () AS total_profit
    FROM category_totals
)
SELECT
    category_name,
    units_sold,
    ROUND(revenue, 2) AS revenue,
    ROUND(gross_profit, 2) AS gross_profit,
    profit_rank,
    ROUND(100 * gross_profit / NULLIF(total_profit, 0), 2) AS profit_share_pct
FROM ranked_categories
ORDER BY profit_rank, category_name;

-- A window function compares each monthly aggregate with the previous month
-- present in the result. Missing months are not silently treated as zero.
WITH monthly_revenue AS (
    SELECT
        date_trunc('month', o.order_date)::DATE AS month_start,
        SUM(oi.quantity * oi.unit_price) AS revenue
    FROM orders AS o
    JOIN order_items AS oi USING (order_id)
    WHERE o.status = 'completed'
    GROUP BY date_trunc('month', o.order_date)::DATE
),
month_comparison AS (
    SELECT
        month_start,
        revenue,
        LAG(revenue) OVER (ORDER BY month_start) AS previous_revenue
    FROM monthly_revenue
)
SELECT
    month_start,
    ROUND(revenue, 2) AS revenue,
    ROUND(previous_revenue, 2) AS previous_revenue,
    ROUND(revenue - previous_revenue, 2) AS absolute_change,
    ROUND(
        100 * (revenue - previous_revenue) / NULLIF(previous_revenue, 0),
        2
    ) AS percentage_change
FROM month_comparison
ORDER BY month_start;

-- Cohort analysis: cohort_month is each customer's first completed purchase.
-- Activity is counted distinctly at customer-month grain to avoid order inflation.
WITH
first_purchase AS (
    SELECT
        customer_id,
        date_trunc('month', MIN(order_date))::DATE AS cohort_month
    FROM orders
    WHERE status = 'completed'
    GROUP BY customer_id
),
customer_activity AS (
    SELECT DISTINCT
        customer_id,
        date_trunc('month', order_date)::DATE AS activity_month
    FROM orders
    WHERE status = 'completed'
),
cohort_sizes AS (
    SELECT cohort_month, COUNT(*) AS cohort_size
    FROM first_purchase
    GROUP BY cohort_month
),
cohort_activity AS (
    SELECT
        fp.cohort_month,
        ca.activity_month,
        (
            EXTRACT(YEAR FROM age(ca.activity_month, fp.cohort_month)) * 12
            + EXTRACT(MONTH FROM age(ca.activity_month, fp.cohort_month))
        )::INTEGER AS month_offset,
        COUNT(DISTINCT ca.customer_id) AS active_customers
    FROM first_purchase AS fp
    JOIN customer_activity AS ca USING (customer_id)
    GROUP BY fp.cohort_month, ca.activity_month
)
SELECT
    a.cohort_month,
    a.activity_month,
    a.month_offset,
    a.active_customers,
    s.cohort_size,
    ROUND(100.0 * a.active_customers / NULLIF(s.cohort_size, 0), 2)
        AS retention_percentage
FROM cohort_activity AS a
JOIN cohort_sizes AS s USING (cohort_month)
WHERE a.month_offset >= 0
ORDER BY a.cohort_month, a.month_offset;

-- Recursive CTE: traverse a category tree and preserve a readable path.
-- The path check prevents repeated category IDs from recurring in a cycle.
WITH RECURSIVE category_tree AS (
    SELECT
        category_id,
        category_name,
        parent_category_id,
        0 AS depth,
        ARRAY[category_id] AS visited_ids,
        category_name::TEXT AS path
    FROM categories
    WHERE parent_category_id IS NULL

    UNION ALL

    SELECT
        child.category_id,
        child.category_name,
        child.parent_category_id,
        parent.depth + 1,
        parent.visited_ids || child.category_id,
        parent.path || ' > ' || child.category_name
    FROM categories AS child
    JOIN category_tree AS parent
      ON child.parent_category_id = parent.category_id
    WHERE NOT child.category_id = ANY(parent.visited_ids)
      AND parent.depth < 50
)
SELECT category_id, category_name, parent_category_id, depth, path
FROM category_tree
ORDER BY path;

-- Aggregate status counts separately from recognized financial value.
-- This makes excluded states visible rather than silently discarding them.
WITH order_line_totals AS (
    SELECT
        o.order_id,
        o.status,
        SUM(oi.quantity * oi.unit_price) AS order_value
    FROM orders AS o
    JOIN order_items AS oi USING (order_id)
    GROUP BY o.order_id, o.status
),
status_summary AS (
    SELECT
        status,
        COUNT(*) AS orders,
        SUM(order_value) AS order_value
    FROM order_line_totals
    GROUP BY status
)
SELECT
    status,
    orders,
    ROUND(order_value, 2) AS order_value,
    ROUND(100.0 * orders / NULLIF(SUM(orders) OVER (), 0), 2)
        AS order_count_share_pct
FROM status_summary
ORDER BY orders DESC, status;

-- Data-integrity failure demonstration.
-- The invalid row references a nonexistent order. The nested block catches
-- the expected violation so the rest of the SQL script can continue.
DO $$
BEGIN
    BEGIN
        INSERT INTO order_items(order_id, product_id, quantity, unit_price)
        VALUES (99999, 1, 1, 100.00);
        RAISE EXCEPTION 'Expected foreign-key violation did not occur';
    EXCEPTION
        WHEN foreign_key_violation THEN
            RAISE NOTICE 'Expected foreign-key violation rejected invalid order item';
    END;
END
$$;

COMMIT;
