-- Advanced SQL: advanced joins, window functions, and query optimization.
-- Target: PostgreSQL 15 or later.
--
-- Run this script in a dedicated learning database. It recreates the
-- advanced_sql_lab schema and all its objects.

BEGIN;

DROP SCHEMA IF EXISTS advanced_sql_lab CASCADE;
CREATE SCHEMA advanced_sql_lab;
SET search_path TO advanced_sql_lab, public;

CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    region TEXT NOT NULL,
    created_at DATE NOT NULL
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL,
    category TEXT NOT NULL,
    list_price NUMERIC(12, 2) NOT NULL CHECK (list_price >= 0)
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(customer_id),
    order_date DATE NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled')
    ),
    shipped_at TIMESTAMPTZ,
    CHECK (shipped_at IS NULL OR status IN ('shipped', 'delivered'))
);

CREATE TABLE order_items (
    order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    discount_rate NUMERIC(5, 4) NOT NULL DEFAULT 0
        CHECK (discount_rate >= 0 AND discount_rate <= 1),
    PRIMARY KEY (order_id, product_id)
);

CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id),
    amount NUMERIC(14, 2) NOT NULL CHECK (amount >= 0),
    payment_status TEXT NOT NULL CHECK (
        payment_status IN ('authorized', 'settled', 'refunded', 'failed')
    ),
    paid_at TIMESTAMPTZ
);

CREATE TABLE support_tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(customer_id),
    order_id BIGINT REFERENCES orders(order_id),
    opened_at TIMESTAMPTZ NOT NULL,
    severity TEXT NOT NULL CHECK (
        severity IN ('low', 'medium', 'high', 'critical')
    ),
    resolved_at TIMESTAMPTZ,
    CHECK (resolved_at IS NULL OR resolved_at >= opened_at)
);

INSERT INTO customers (customer_id, customer_name, region, created_at) VALUES
    (1, 'Aarav Sharma', 'North', '2025-01-10'),
    (2, 'Meera Singh', 'South', '2025-02-15'),
    (3, 'Kabir Verma', 'West', '2025-03-20'),
    (4, 'Ananya Rao', 'North', '2025-04-05'),
    (5, 'Ishaan Gupta', 'East', '2025-05-18'),
    (6, 'Diya Nair', 'South', '2025-06-22'),
    (7, 'Noah Roy', 'East', '2025-07-10');

INSERT INTO products (product_id, product_name, category, list_price) VALUES
    (1, 'Laptop', 'Electronics', 75000.00),
    (2, 'Monitor', 'Electronics', 18000.00),
    (3, 'Office Chair', 'Furniture', 12000.00),
    (4, 'Desk Lamp', 'Furniture', 2500.00),
    (5, 'Keyboard', 'Accessories', 3500.00);

INSERT INTO orders (
    order_id, customer_id, order_date, status, shipped_at
) VALUES
    (101, 1, '2025-01-12', 'delivered', '2025-01-13 10:00:00+00'),
    (102, 1, '2025-02-10', 'delivered', '2025-02-11 10:00:00+00'),
    (103, 2, '2025-02-15', 'shipped', '2025-02-16 10:00:00+00'),
    (104, 2, '2025-03-01', 'cancelled', NULL),
    (105, 3, '2025-03-12', 'delivered', '2025-03-13 10:00:00+00'),
    (106, 3, '2025-04-20', 'paid', NULL),
    (107, 4, '2025-05-02', 'delivered', '2025-05-03 10:00:00+00'),
    (108, 5, '2025-05-19', 'pending', NULL),
    (109, 1, '2025-06-11', 'delivered', '2025-06-12 10:00:00+00'),
    (110, 6, '2025-06-22', 'delivered', '2025-06-23 10:00:00+00'),
    (111, 4, '2025-07-05', 'delivered', '2025-07-06 10:00:00+00');

INSERT INTO order_items (
    order_id, product_id, quantity, unit_price, discount_rate
) VALUES
    (101, 1, 1, 75000.00, 0.05),
    (101, 5, 2, 3500.00, 0.00),
    (102, 2, 2, 18000.00, 0.10),
    (103, 3, 1, 12000.00, 0.00),
    (103, 4, 2, 2500.00, 0.00),
    (104, 5, 1, 3500.00, 0.00),
    (105, 1, 1, 75000.00, 0.00),
    (106, 3, 2, 12000.00, 0.05),
    (107, 2, 1, 18000.00, 0.00),
    (107, 4, 4, 2500.00, 0.10),
    (108, 5, 3, 3500.00, 0.00),
    (109, 1, 1, 75000.00, 0.10),
    (110, 3, 1, 12000.00, 0.00),
    (110, 5, 1, 3500.00, 0.00),
    (111, 2, 1, 18000.00, 0.00);

INSERT INTO payments (
    payment_id, order_id, amount, payment_status, paid_at
) VALUES
    (1, 101, 81750.00, 'settled', '2025-01-12 12:00:00+00'),
    (2, 102, 32400.00, 'settled', '2025-02-10 12:00:00+00'),
    (3, 103, 17000.00, 'authorized', NULL),
    (4, 104, 3500.00, 'refunded', '2025-03-01 12:00:00+00'),
    (5, 105, 75000.00, 'settled', '2025-03-12 12:00:00+00'),
    (6, 106, 22800.00, 'authorized', NULL),
    (7, 107, 27000.00, 'settled', '2025-05-02 12:00:00+00'),
    (8, 108, 10500.00, 'authorized', NULL),
    (9, 109, 67500.00, 'settled', '2025-06-11 12:00:00+00'),
    (10, 110, 15500.00, 'settled', '2025-06-22 12:00:00+00'),
    (11, 111, 18000.00, 'settled', '2025-07-05 12:00:00+00');

INSERT INTO support_tickets (
    ticket_id, customer_id, order_id, opened_at, severity, resolved_at
) VALUES
    (1, 1, 102, '2025-02-12 09:00:00+00', 'medium', '2025-02-14 09:00:00+00'),
    (2, 2, 103, '2025-02-20 09:00:00+00', 'high', NULL),
    (3, 3, 105, '2025-03-15 09:00:00+00', 'low', '2025-03-16 09:00:00+00'),
    (4, 4, 107, '2025-05-05 09:00:00+00', 'critical', NULL),
    (5, 1, 109, '2025-06-12 09:00:00+00', 'high', '2025-06-13 09:00:00+00'),
    (6, 6, 110, '2025-06-23 09:00:00+00', 'medium', NULL);

-- Advanced joins: aggregate each independent one-to-many relationship before
-- joining it to the order. Otherwise item rows multiply payment rows.
WITH item_totals AS (
    SELECT
        order_id,
        SUM(quantity * unit_price * (1 - discount_rate)) AS net_total
    FROM order_items
    GROUP BY order_id
),
payment_totals AS (
    SELECT
        order_id,
        SUM(amount) FILTER (WHERE payment_status = 'settled') AS settled_total
    FROM payments
    GROUP BY order_id
),
ticket_totals AS (
    SELECT
        order_id,
        COUNT(*) AS ticket_count,
        COUNT(*) FILTER (WHERE resolved_at IS NULL) AS open_ticket_count
    FROM support_tickets
    WHERE order_id IS NOT NULL
    GROUP BY order_id
)
SELECT
    o.order_id,
    c.customer_name,
    o.status,
    COALESCE(i.net_total, 0) AS net_total,
    COALESCE(p.settled_total, 0) AS settled_total,
    COALESCE(t.ticket_count, 0) AS ticket_count,
    COALESCE(t.open_ticket_count, 0) AS open_ticket_count
FROM orders AS o
JOIN customers AS c ON c.customer_id = o.customer_id
LEFT JOIN item_totals AS i ON i.order_id = o.order_id
LEFT JOIN payment_totals AS p ON p.order_id = o.order_id
LEFT JOIN ticket_totals AS t ON t.order_id = o.order_id
ORDER BY o.order_id;

-- Outer join semantics: the delivered-order predicate belongs in ON if
-- customers without delivered orders must remain in the result.
SELECT
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS delivered_order_count
FROM customers AS c
LEFT JOIN orders AS o
  ON o.customer_id = c.customer_id
 AND o.status = 'delivered'
GROUP BY c.customer_id, c.customer_name
ORDER BY delivered_order_count, c.customer_id;

-- NOT EXISTS is a robust anti-join, even if the subquery's key can be NULL.
SELECT c.customer_id, c.customer_name
FROM customers AS c
WHERE NOT EXISTS (
    SELECT 1
    FROM support_tickets AS t
    WHERE t.customer_id = c.customer_id
)
ORDER BY c.customer_id;

-- LATERAL allows a correlated top-one lookup per customer. The index created
-- below supports filtering and descending date order.
SELECT
    c.customer_id,
    c.customer_name,
    latest.order_id,
    latest.order_date,
    latest.status
FROM customers AS c
LEFT JOIN LATERAL (
    SELECT o.order_id, o.order_date, o.status
    FROM orders AS o
    WHERE o.customer_id = c.customer_id
    ORDER BY o.order_date DESC, o.order_id DESC
    LIMIT 1
) AS latest ON TRUE
ORDER BY c.customer_id;

-- Window functions: ranking and distribution.
WITH customer_revenue AS (
    SELECT
        c.customer_id,
        c.customer_name,
        c.region,
        COALESCE(
            SUM(oi.quantity * oi.unit_price * (1 - oi.discount_rate))
                FILTER (WHERE o.status <> 'cancelled'),
            0
        ) AS revenue
    FROM customers AS c
    LEFT JOIN orders AS o ON o.customer_id = c.customer_id
    LEFT JOIN order_items AS oi ON oi.order_id = o.order_id
    GROUP BY c.customer_id, c.customer_name, c.region
)
SELECT
    customer_id,
    customer_name,
    region,
    revenue,
    RANK() OVER (
        PARTITION BY region ORDER BY revenue DESC
    ) AS regional_rank,
    DENSE_RANK() OVER (
        ORDER BY revenue DESC
    ) AS overall_dense_rank,
    ROW_NUMBER() OVER (
        PARTITION BY region ORDER BY revenue DESC, customer_id
    ) AS deterministic_row_number,
    NTILE(4) OVER (ORDER BY revenue DESC) AS revenue_quartile
FROM customer_revenue
ORDER BY region, regional_rank, customer_id;

-- Running totals and trailing averages use explicit ROWS frames. Here each
-- input row represents one calendar date after daily aggregation.
WITH daily_revenue AS (
    SELECT
        o.order_date,
        SUM(oi.quantity * oi.unit_price * (1 - oi.discount_rate)) AS revenue
    FROM orders AS o
    JOIN order_items AS oi ON oi.order_id = o.order_id
    WHERE o.status = 'delivered'
    GROUP BY o.order_date
)
SELECT
    order_date,
    revenue,
    SUM(revenue) OVER (
        ORDER BY order_date
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS running_revenue,
    AVG(revenue) OVER (
        ORDER BY order_date
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS trailing_three_observation_average,
    LAG(revenue) OVER (ORDER BY order_date) AS previous_observation_revenue,
    revenue - LAG(revenue) OVER (ORDER BY order_date) AS change_from_previous
FROM daily_revenue
ORDER BY order_date;

-- Window functions do not collapse rows. Use a subquery to filter by a
-- computed window value because PostgreSQL cannot use a window expression
-- directly in WHERE.
WITH ranked_orders AS (
    SELECT
        o.*,
        ROW_NUMBER() OVER (
            PARTITION BY customer_id
            ORDER BY order_date DESC, order_id DESC
        ) AS newest_first
    FROM orders AS o
)
SELECT order_id, customer_id, order_date, status
FROM ranked_orders
WHERE newest_first = 1
ORDER BY customer_id;

-- Query optimization: index definitions should follow actual filter, join,
-- and ordering patterns. A multicolumn B-tree is most useful when leading
-- columns align with the query's restrictions.
CREATE INDEX idx_orders_customer_date
    ON orders (customer_id, order_date DESC, order_id DESC);

CREATE INDEX idx_orders_status_date
    ON orders (status, order_date);

CREATE INDEX idx_order_items_product
    ON order_items (product_id, order_id);

CREATE INDEX idx_payments_order_status
    ON payments (order_id, payment_status);

CREATE INDEX idx_support_tickets_customer_open
    ON support_tickets (customer_id, opened_at DESC)
    WHERE resolved_at IS NULL;

-- ANALYZE refreshes planner statistics after loading representative data.
ANALYZE customers;
ANALYZE orders;
ANALYZE order_items;
ANALYZE payments;
ANALYZE support_tickets;

-- Compare this plan with the same query before the composite index. EXPLAIN
-- shows estimates without executing the statement.
EXPLAIN (COSTS, VERBOSE)
SELECT order_id, order_date, status
FROM orders
WHERE customer_id = 1
  AND order_date >= DATE '2025-01-01'
  AND order_date < DATE '2025-07-01'
ORDER BY order_date DESC, order_id DESC;

-- EXPLAIN ANALYZE executes the query. BUFFERS exposes buffer activity.
-- Runtime and plans on this small dataset are illustrative, not benchmarks.
EXPLAIN (ANALYZE, BUFFERS, VERBOSE)
SELECT order_id, order_date, status
FROM orders
WHERE customer_id = 1
  AND order_date >= DATE '2025-01-01'
  AND order_date < DATE '2025-07-01'
ORDER BY order_date DESC, order_id DESC;

-- Sargable range filtering keeps the indexed column unwrapped in the predicate.
-- This half-open interval also avoids end-of-day timestamp boundary mistakes.
EXPLAIN (COSTS)
SELECT order_id, order_date
FROM orders
WHERE order_date >= DATE '2025-05-01'
  AND order_date < DATE '2025-06-01'
ORDER BY order_date;

-- A materialized view persists expensive aggregates between refreshes.
-- It is useful for read-heavy reporting, but its contents become stale until
-- refreshed. PostgreSQL can concurrently refresh only under suitable unique
-- index and populated-view conditions.
CREATE MATERIALIZED VIEW monthly_regional_revenue AS
SELECT
    DATE_TRUNC('month', o.order_date)::DATE AS month_start,
    c.region,
    SUM(oi.quantity * oi.unit_price * (1 - oi.discount_rate)) AS revenue
FROM orders AS o
JOIN customers AS c ON c.customer_id = o.customer_id
JOIN order_items AS oi ON oi.order_id = o.order_id
WHERE o.status = 'delivered'
GROUP BY DATE_TRUNC('month', o.order_date)::DATE, c.region;

CREATE UNIQUE INDEX idx_monthly_region
    ON monthly_regional_revenue (month_start, region);

SELECT month_start, region, revenue
FROM monthly_regional_revenue
ORDER BY month_start, region;

REFRESH MATERIALIZED VIEW monthly_regional_revenue;

-- Constraint demonstration: this insert violates quantity > 0 and fails.
-- It is isolated in a savepoint so the surrounding script can continue.
SAVEPOINT invalid_quantity_demo;

DO $$
BEGIN
    BEGIN
        INSERT INTO order_items (
            order_id, product_id, quantity, unit_price, discount_rate
        )
        VALUES (101, 2, 0, 18000.00, 0.00);
    EXCEPTION
        WHEN check_violation THEN
            RAISE NOTICE 'Invalid quantity rejected by CHECK constraint.';
    END;
END;
$$;

ROLLBACK TO SAVEPOINT invalid_quantity_demo;
RELEASE SAVEPOINT invalid_quantity_demo;

-- Transactional workflow: change the order state and insert an audit-like
-- payment record together. If either operation fails, both are rolled back.
SAVEPOINT settlement_demo;

DO $$
BEGIN
    BEGIN
        INSERT INTO payments (
            order_id, amount, payment_status, paid_at
        )
        VALUES (106, 22800.00, 'settled', CURRENT_TIMESTAMP);

        UPDATE orders
        SET status = 'shipped',
            shipped_at = CURRENT_TIMESTAMP
        WHERE order_id = 106
          AND status = 'paid';

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Order 106 was not in the paid state';
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RAISE NOTICE 'Settlement transaction rejected: %', SQLERRM;
            RAISE;
    END;
END;
$$;

-- Roll back the demonstration transaction to preserve the original sample.
ROLLBACK TO SAVEPOINT settlement_demo;
RELEASE SAVEPOINT settlement_demo;

COMMIT;
